{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "universal-chart.fullname" . }}
  labels:
    {{- include "universal-chart.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "universal-chart.fullname" $ }}
                port:
                  {{- $servicePort := default (include "universal-chart.defaultServiceBackendPort" $) .servicePort -}}
                  {{- if kindIs "map" $servicePort }}
                  {{- with $servicePort.name }}
                  name: {{ . }}
                  {{- end }}
                  {{- with $servicePort.number }}
                  number: {{ . }}
                  {{- end }}
                  {{- else }}
                  {{- $servicePortValue := printf "%v" $servicePort -}}
                  {{- if regexMatch "^[0-9]+$" $servicePortValue }}
                  number: {{ int $servicePortValue }}
                  {{- else }}
                  name: {{ $servicePortValue }}
                  {{- end }}
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
