name: Build and Release Helm Chart

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Install Helm
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0

    # Package the Helm chart
    - name: Package Helm chart
      run: helm package .

    # Create GitHub Release and upload Helm chart artifact
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: ./universal-chart-*.tgz